### PR TITLE
Survey templates

### PR DESCRIPTION
**Pull request by finnss**
Adds the option to load templates in surveys to reduce the amount of repetetive work survey creators have to do.

Does so using url params: `/surveys/add/?templateType=company_presentation` will issue a fetch for the template used for company presentations, and then use that to initialize the form. Regular users do this by clicking a new "Use template" button, which has a dropdown containing each type from the possible event types found in `events/utils`.

skjermbilde 2018-02-21 kl 02 21 46

Clicking an item simply links to an url on the form above and reinitializes the form.

Because clicking such an item overrides all changes users have made, I figured there should be a confirm modal. However, the confirm modal component didn't seem to cooperate at all, so for now I use the native `if (confirm("er du sikker?")) { ... }`.

skjermbilde 2018-02-21 kl 02 32 35

This works for both adding and editing: `/surveys/someId/edit/?templateType=other` is also implemented. Overriding existing surveys with templates is probably less common functionality than while creating a new survey, but it's there. Loading from an event while editing is **not** supported, as I didn't see what kind of use case this would cover.

Also adds a list view of all templates, separating them from the regular list view (templates aren't included in the regular list view). 

skjermbilde 2018-02-21 kl 02 26 47

Because templates are just regular surveys with an additional field set, they can be edited like any other survey. 

**Also adds another cool feature**: initializing surveys from an event id. `/surveys/add/?event=50` will not only set the `survey.event` as expected, but also initialize the form _based on the template for the eventType_ of event 50. `/surveys/add/?event=50` without any inputs:

skjermbilde 2018-02-21 kl 02 30 38

It also sets the "Active from" field to `event.endTime`.

### CODE REVIEW

File: app/routes/surveys/AddSurveyRoute.js [hunk 1]
```diff
@@ -1,31 +1,85 @@
...
-  moment()
-    .startOf('day')
-    .add({ hours, minutes })
-    .toISOString();
+const loadData = (props, dispatch) => {
+  const { template, event } = props.location.query;
+  if (event) {
+    return dispatch(fetchEvent(event)).then(
+      result =>
+        result.success &&
```
Comment (ekmartin) [inline app/routes/surveys/AddSurveyRoute.js]: do you need the `result.success` here? wouldn't it throw if the result wasn't successful?

File: app/routes/surveys/AddSurveyRoute.js [hunk 2]
```diff
@@ -1,31 +1,85 @@
...
+        dispatch(fetchTemplate(result.payload.entities.events[event].eventType))
```
Comment (ekmartin) [inline app/routes/surveys/AddSurveyRoute.js]: if the only reason you're fetching the event is to retrieve the template, maybe we should have an API endpoint on the backend for doing so? `/api/v1/events/10/survey-template` or something like that? up to you, but might save you some code :p

File: app/routes/surveys/AddSurveyRoute.js [hunk 3]
```diff
@@ -37,5 +91,10 @@ const mapDispatchToProps = {
 
 export default compose(
   replaceUnlessLoggedIn(LoginPage),
+  prepare(loadData, [
+    'notFetching',
```
Comment (ekmartin) [inline app/routes/surveys/AddSurveyRoute.js]: why do you need `notFetching` in here?

File: app/routes/surveys/AddSurveyRoute.js [hunk 4]
```diff
@@ -1,31 +1,85 @@
...
 
 const mapStateToProps = (state, props) => {
+  const notFetching = !state.surveys.fetching && !state.events.fetching;
+  const { templateType, event } = props.location.query;
+
+  const fullEvent = selectEventById(state, { eventId: event });
+
+  const template = selectSurveyTemplate(state, {
+    ...props,
+    templateType: templateType || fullEvent.eventType
```
Comment (ekmartin) [inline app/routes/surveys/AddSurveyRoute.js]: if you're always fetching the template, when would `fullEvent.eventType` be used?

File: app/routes/surveys/AddSurveyRoute.js [hunk 5]
```diff
@@ -1,31 +1,85 @@
...
+  });
+
+  const initialEvent = event
```
Comment (ekmartin) [inline app/routes/surveys/AddSurveyRoute.js]: why can an event be both an object and a string?

File: app/routes/surveys/AddSurveyRoute.js (hunk 4 above)
Comment (ekmartin) [reply app/routes/surveys/AddSurveyRoute.js]: or is that in the case where there's no template at all?

File: app/routes/surveys/AddSurveyRoute.js [hunk 6]
```diff
@@ -1,31 +1,85 @@
...
+        value: fullEvent.id,
+        label: fullEvent.title
+      }
+    : '';
+  const activeFrom = event ? fullEvent.endTime : defaultActiveFrom(12, 0);
+
+  let initialValues = null;
+  if (
+    !(
+      ((templateType || event) && !template) ||
```
Comment (ekmartin) [inline app/routes/surveys/AddSurveyRoute.js]: this seems painful, what's going on here?

File: app/routes/surveys/AddSurveyRoute.js [hunk 7]
```diff
@@ -1,31 +1,85 @@
...
-      isClone: true,
-      questions: [initialQuestion]
-    },
+    template,
+    initialValues,
     survey: {
-      questions: []
-    }
+      questions: template ? template.questions : [],
+      event: event && fullEvent
```
Comment (ekmartin) [inline app/routes/surveys/AddSurveyRoute.js]: couldn't this just be `event: fullEvent`?

File: app/routes/surveys/TemplatesRoute.js [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+  addSurvey,
+  deleteSurvey,
+  push
+};
+
+export default compose(
+  replaceUnlessLoggedIn(LoginPage),
+  prepare(loadData),
+  connect(mapStateToProps, mapDispatchToProps),
+  loadingIndicator(['notFetching', 'surveys'])
```
Comment (ekmartin) [inline app/routes/surveys/TemplatesRoute.js]: do you need `'surveys` here? doens't `notFetching` cover that

**Comment by ekmartin** [comment]
good job :) nice that it fetches the template automatically for events.

File: app/routes/surveys/AddSurveyRoute.js (hunk 1 above)
Comment (finnss) [reply app/routes/surveys/AddSurveyRoute.js]: Okay? I figured since `result` includes a boolean `success` there were cases where it was false I'd have to handle, but I wouldn't be surprised if that's taken care of in middleware or something.

File: app/routes/surveys/AddSurveyRoute.js (hunk 3 above)
Comment (finnss) [reply app/routes/surveys/AddSurveyRoute.js]: I suppose that should be in a `loadingIndicator`

File: app/routes/surveys/AddSurveyRoute.js (hunk 4 above)
Comment (finnss) [reply app/routes/surveys/AddSurveyRoute.js]: `templateType` is the url param, which is undefined in the `surveys/add/?event=50` case. So this is for the case where template is fetched based on event type.

File: app/routes/surveys/AddSurveyRoute.js (hunk 2 above)
Comment (finnss) [reply app/routes/surveys/AddSurveyRoute.js]: I use it for setting initialValues `survey.event` (which requires title for the autocomplete selector)  and `activeFrom = event.endTime` too. I suppose I fetch quite a bit more information about the event than I need, but I figured that wasn't a huge deal? You'll only ever do one such fetch at a time.

File: app/routes/surveys/AddSurveyRoute.js (hunk 5 above)
Comment (finnss) [reply app/routes/surveys/AddSurveyRoute.js]: I think that's how the `SelectInput` autocomplete thing works? Sending an empty string makes it empty, while sending an object on the form
```
{
        value: fullEvent.id,
        label: fullEvent.title
}
```
makes it select that event by default. I suppose that instead of an empty string I could send
```
{
        value: '',
        label: ''
}
```
I just didn't see the need or advantage

File: app/routes/surveys/AddSurveyRoute.js (hunk 7 above)
Comment (finnss) [reply app/routes/surveys/AddSurveyRoute.js]: The event selector returns an empty object if it doesn't find anything, and I think I do some `if (event) { ... }` later on which would evaluate to true. I didn't want to deal with any `object 'event' has no attribute 'title'` error messages. Think that's bad practise?

File: app/routes/surveys/AddSurveyRoute.js (hunk 6 above)
Comment (finnss) [reply app/routes/surveys/AddSurveyRoute.js]: Yeah I know, I've been thinking about how to fix this. The purpose is to make sure to return `initialValues: null` if either the event or the template is being fetched. Without this check, the logic would use `event: undefined` and/or `template: undefined` to assume we were in a regular case without any url params. That was a problem, because once `initialValues` have been passed to redux-form as anything else than null, it didn't seem to automatically reinitialize when `initialValues` changed. I suppose `if (!notFetching) { ... }` would be equivalent, I've just had some bad experience with the `fetching` flag being inconsistent. I'll check if it works

File: app/routes/surveys/EditSurveyRoute.js [hunk 9]
```diff
@@ -1,43 +1,82 @@
...
+  const templateType = props.location.query.templateType;
+  const template = selectSurveyTemplate(state, { ...props, templateType });
+
+  const initialEvent = survey.event && {
+    value: survey.event.id,
+    label: survey.event.title
+  };
+
+  let initialValues = null;
+  if (notFetching && !(templateType && !template)) {
```
Comment (finnss) [inline app/routes/surveys/EditSurveyRoute.js]: I tried having just `notFetching` here, but it really seemed unpredictable and sporadic. It _usually_ does the trick, but I can't seem to see the pattern to when it decides to say it's done fetching despite `template` not being available in state yet. Could be a problem somewhere else in the stack but I couldn't find it.
